---
- hosts: tomcat
  remote_user: centos
  become: yes
  become_method: sudo
  
  tasks: 
  - maven_artifact:
       group_id=bharath.org
       artifact_id=application
       extension=war
       repository_url=http://54.153.77.32:8080/nexus/content/repositories/snapshots/
       dest=/usr/local/tomcat7/webapps/web-app.war
