---
- hosts: 172.31.5.115
  user: centos
  become: true
  connection: ssh
  
  tasks:
  - name: Deploy War File
    maven_artifact:
      group_id: bharath.org
      artifact_id: application
      repository_url: 'http://54.153.77.32:8080/nexus/'
      username: admin
      password: admin
      dest: ~
