---
- hosts: all
  tasks:
  - name: Deploy War File
    maven_artifact: group_id=org.bharath artifact_id=application extension=war repository_url=http://ec2-54-153-77-32.us-west-1.compute.amazonaws.com:8080/nexus-2.14.5-02/content/repositories/snapshots/ username=admin password=admin123  dest=~/cd/
