---
- hosts: tomcat
  remote_user: centos
  become: yes
  become_method: sudo
  
  tasks:
  - name: Deploy War File
    maven_artifact: group_id=bharath.org artifact_id=applications extension=war repository_url=http://54.153.77.32:8080/nexus/content/repositories/snapshots/bharath/org/application/1.0-SNAPSHOT/ dest=/usr/local/tomcat7/webapps
/web-app.war
